# Frontend Dockerfile

# Usa Node 20
FROM node:20-alpine

WORKDIR /usr/src/app

# Copia package.json e package-lock.json
COPY package*.json ./

# Installa dipendenze
RUN npm ci

# Copia tutto il codice
COPY . .

# Costruisci Next.js
RUN npm run build

# Esponi porta
EXPOSE 3000

# Avvia app
CMD ["npm", "run", "dev"]
